name: "telegram weather bot"

on:
    schedule: 
        - cron: '05 20 * * *' 
    
jobs:
    bot:
        runs-on: ubuntu-latest
        steps:

        - uses: actions/checkout@v1
        - name: setup node
          uses: actions/setup-node@v1
        - name: install npm  dependencies
          run: npm install 
        - name: run code
          run: node index.js
          env:
            WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN}}
            TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN}}
            TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID}}


